import { Appointment } from "./typing";

export const appointments: Appointment[] = [
  {
    id: "1",
    patient: {
      name: "John Doe",
      avatar: "/path/to/avatar1.jpg",
      age: 25,
      gender: "Male",
      contact: "123-456-7890",
    },
    ref: "REF001",
    deviceId: "DEV001",
    status: "Ongoing",
  },
  {
    id: "2",
    patient: {
      name: "Jane Smith",
      avatar: "/path/to/avatar2.jpg",
      age: 32,
      gender: "Female",
      contact: "987-654-3210",
    },
    ref: "REF002",
    deviceId: "DEV002",
    status: "Completed",
  },
  {
    id: "3",
    patient: {
      name: "Alex Johnson",
      avatar: "/path/to/avatar3.jpg",
      age: 28,
      gender: "Male",
      contact: "555-123-4567",
    },
    ref: "REF003",
    deviceId: "DEV003",
    status: "Postponed",
  },
  {
    id: "4",
    patient: {
      name: "Emily Brown",
      avatar: "/path/to/avatar4.jpg",
      age: 22,
      gender: "Female",
      contact: "333-222-1111",
    },
    ref: "REF004",
    deviceId: "DEV004",
    status: "Due",
  },
  {
    id: "5",
    patient: {
      name: "Michael White",
      avatar: "/path/to/avatar5.jpg",
      age: 45,
      gender: "Male",
      contact: "444-555-6666",
    },
    ref: "REF005",
    deviceId: "DEV005",
    status: "Ongoing",
  },
  {
    id: "6",
    patient: {
      name: "Olivia Green",
      avatar: "/path/to/avatar6.jpg",
      age: 30,
      gender: "Female",
      contact: "111-222-3333",
    },
    ref: "REF006",
    deviceId: "DEV006",
    status: "Completed",
  },
  {
    id: "7",
    patient: {
      name: "William Black",
      avatar: "/path/to/avatar7.jpg",
      age: 39,
      gender: "Male",
      contact: "777-888-9999",
    },
    ref: "REF007",
    deviceId: "DEV007",
    status: "Postponed",
  },
  {
    id: "8",
    patient: {
      name: "Sophia Brown",
      avatar: "/path/to/avatar8.jpg",
      age: 34,
      gender: "Female",
      contact: "000-111-2222",
    },
    ref: "REF008",
    deviceId: "DEV008",
    status: "Due",
  },
  {
    id: "9",
    patient: {
      name: "David Blue",
      avatar: "/path/to/avatar9.jpg",
      age: 27,
      gender: "Male",
      contact: "888-777-6666",
    },
    ref: "REF009",
    deviceId: "DEV009",
    status: "Ongoing",
  },
  {
    id: "10",
    patient: {
      name: "Chloe Violet",
      avatar: "/path/to/avatar10.jpg",
      age: 50,
      gender: "Female",
      contact: "222-333-4444",
    },
    ref: "REF010",
    deviceId: "DEV010",
    status: "Completed",
  },
  {
    id: "11",
    patient: {
      name: "Liam Young",
      avatar: "/path/to/avatar11.jpg",
      age: 29,
      gender: "Male",
      contact: "999-888-7777",
    },
    ref: "REF011",
    deviceId: "DEV011",
    status: "Postponed",
  },
  {
    id: "12",
    patient: {
      name: "Zoe Gray",
      avatar: "/path/to/avatar12.jpg",
      age: 31,
      gender: "Female",
      contact: "123-987-6543",
    },
    ref: "REF012",
    deviceId: "DEV012",
    status: "Due",
  },
  {
    id: "13",
    patient: {
      name: "Jack Blue",
      avatar: "/path/to/avatar13.jpg",
      age: 42,
      gender: "Male",
      contact: "111-555-2222",
    },
    ref: "REF013",
    deviceId: "DEV013",
    status: "Ongoing",
  },
  {
    id: "14",
    patient: {
      name: "Grace White",
      avatar: "/path/to/avatar14.jpg",
      age: 27,
      gender: "Female",
      contact: "444-999-8888",
    },
    ref: "REF014",
    deviceId: "DEV014",
    status: "Completed",
  },
  {
    id: "15",
    patient: {
      name: "Henry Green",
      avatar: "/path/to/avatar15.jpg",
      age: 24,
      gender: "Male",
      contact: "555-666-3333",
    },
    ref: "REF015",
    deviceId: "DEV015",
    status: "Postponed",
  },
  {
    id: "16",
    patient: {
      name: "Ella Black",
      avatar: "/path/to/avatar16.jpg",
      age: 36,
      gender: "Female",
      contact: "222-777-4444",
    },
    ref: "REF016",
    deviceId: "DEV016",
    status: "Due",
  },
  {
    id: "17",
    patient: {
      name: "Daniel Brown",
      avatar: "/path/to/avatar17.jpg",
      age: 48,
      gender: "Male",
      contact: "999-333-5555",
    },
    ref: "REF017",
    deviceId: "DEV017",
    status: "Ongoing",
  },
  {
    id: "18",
    patient: {
      name: "Ava Blue",
      avatar: "/path/to/avatar18.jpg",
      age: 26,
      gender: "Female",
      contact: "333-222-4444",
    },
    ref: "REF018",
    deviceId: "DEV018",
    status: "Completed",
  },
  {
    id: "19",
    patient: {
      name: "James Violet",
      avatar: "/path/to/avatar19.jpg",
      age: 37,
      gender: "Male",
      contact: "444-222-6666",
    },
    ref: "REF019",
    deviceId: "DEV019",
    status: "Postponed",
  },
  {
    id: "20",
    patient: {
      name: "Mia White",
      avatar: "/path/to/avatar20.jpg",
      age: 33,
      gender: "Female",
      contact: "888-555-1111",
    },
    ref: "REF020",
    deviceId: "DEV020",
    status: "Due",
  },
  {
    id: "21",
    patient: {
      name: "George Black",
      avatar: "/path/to/avatar21.jpg",
      age: 44,
      gender: "Male",
      contact: "111-444-3333",
    },
    ref: "REF021",
    deviceId: "DEV021",
    status: "Ongoing",
  },
  {
    id: "22",
    patient: {
      name: "Lucy Gray",
      avatar: "/path/to/avatar22.jpg",
      age: 20,
      gender: "Female",
      contact: "777-666-8888",
    },
    ref: "REF022",
    deviceId: "DEV022",
    status: "Completed",
  },
  {
    id: "23",
    patient: {
      name: "Ethan Green",
      avatar: "/path/to/avatar23.jpg",
      age: 35,
      gender: "Male",
      contact: "222-999-1111",
    },
    ref: "REF023",
    deviceId: "DEV023",
    status: "Postponed",
  },
  {
    id: "24",
    patient: {
      name: "Lily Brown",
      avatar: "/path/to/avatar24.jpg",
      age: 28,
      gender: "Female",
      contact: "333-111-7777",
    },
    ref: "REF024",
    deviceId: "DEV024",
    status: "Due",
  },
  {
    id: "25",
    patient: {
      name: "Matthew Blue",
      avatar: "/path/to/avatar25.jpg",
      age: 47,
      gender: "Male",
      contact: "555-888-4444",
    },
    ref: "REF025",
    deviceId: "DEV025",
    status: "Ongoing",
  },
  {
    id: "26",
    patient: {
      name: "Amelia Violet",
      avatar: "/path/to/avatar26.jpg",
      age: 29,
      gender: "Female",
      contact: "111-333-5555",
    },
    ref: "REF026",
    deviceId: "DEV026",
    status: "Completed",
  },
  {
    id: "27",
    patient: {
      name: "Ryan Young",
      avatar: "/path/to/avatar27.jpg",
      age: 38,
      gender: "Male",
      contact: "777-555-9999",
    },
    ref: "REF027",
    deviceId: "DEV027",
    status: "Postponed",
  },
  {
    id: "28",
    patient: {
      name: "Sophia Gray",
      avatar: "/path/to/avatar28.jpg",
      age: 21,
      gender: "Female",
      contact: "222-666-1111",
    },
    ref: "REF028",
    deviceId: "DEV028",
    status: "Due",
  },
  {
    id: "29",
    patient: {
      name: "Nathan White",
      avatar: "/path/to/avatar29.jpg",
      age: 41,
      gender: "Male",
      contact: "888-333-4444",
    },
    ref: "REF029",
    deviceId: "DEV029",
    status: "Ongoing",
  },
  {
    id: "30",
    patient: {
      name: "Isabella Green",
      avatar: "/path/to/avatar30.jpg",
      age: 31,
      gender: "Female",
      contact: "111-222-7777",
    },
    ref: "REF030",
    deviceId: "DEV030",
    status: "Completed",
  },
  {
    id: "31",
    patient: {
      name: "Owen Black",
      avatar: "/path/to/avatar31.jpg",
      age: 34,
      gender: "Male",
      contact: "555-444-1111",
    },
    ref: "REF031",
    deviceId: "DEV031",
    status: "Postponed",
  },
  {
    id: "32",
    patient: {
      name: "Emma Brown",
      avatar: "/path/to/avatar32.jpg",
      age: 27,
      gender: "Female",
      contact: "999-555-6666",
    },
    ref: "REF032",
    deviceId: "DEV032",
    status: "Due",
  },
  {
    id: "33",
    patient: {
      name: "Luke Gray",
      avatar: "/path/to/avatar33.jpg",
      age: 46,
      gender: "Male",
      contact: "222-333-9999",
    },
    ref: "REF033",
    deviceId: "DEV033",
    status: "Ongoing",
  },
  {
    id: "34",
    patient: {
      name: "Mila Blue",
      avatar: "/path/to/avatar34.jpg",
      age: 24,
      gender: "Female",
      contact: "111-888-5555",
    },
    ref: "REF034",
    deviceId: "DEV034",
    status: "Completed",
  },
  {
    id: "35",
    patient: {
      name: "Oliver Violet",
      avatar: "/path/to/avatar35.jpg",
      age: 40,
      gender: "Male",
      contact: "777-222-1111",
    },
    ref: "REF035",
    deviceId: "DEV035",
    status: "Postponed",
  },
  {
    id: "36",
    patient: {
      name: "Luna Green",
      avatar: "/path/to/avatar36.jpg",
      age: 32,
      gender: "Female",
      contact: "333-444-2222",
    },
    ref: "REF036",
    deviceId: "DEV036",
    status: "Due",
  },
  {
    id: "37",
    patient: {
      name: "Charlie Black",
      avatar: "/path/to/avatar37.jpg",
      age: 23,
      gender: "Male",
      contact: "888-111-6666",
    },
    ref: "REF037",
    deviceId: "DEV037",
    status: "Ongoing",
  },
  {
    id: "38",
    patient: {
      name: "Avery Brown",
      avatar: "/path/to/avatar38.jpg",
      age: 49,
      gender: "Female",
      contact: "111-555-3333",
    },
    ref: "REF038",
    deviceId: "DEV038",
    status: "Completed",
  },
  {
    id: "39",
    patient: {
      name: "Samuel Blue",
      avatar: "/path/to/avatar39.jpg",
      age: 36,
      gender: "Male",
      contact: "444-999-1111",
    },
    ref: "REF039",
    deviceId: "DEV039",
    status: "Postponed",
  },
  {
    id: "40",
    patient: {
      name: "Scarlett White",
      avatar: "/path/to/avatar40.jpg",
      age: 30,
      gender: "Female",
      contact: "777-444-8888",
    },
    ref: "REF040",
    deviceId: "DEV040",
    status: "Due",
  },
  {
    id: "41",
    patient: {
      name: "Elijah Gray",
      avatar: "/path/to/avatar41.jpg",
      age: 43,
      gender: "Male",
      contact: "555-222-3333",
    },
    ref: "REF041",
    deviceId: "DEV041",
    status: "Ongoing",
  },
  {
    id: "42",
    patient: {
      name: "Isla Blue",
      avatar: "/path/to/avatar42.jpg",
      age: 35,
      gender: "Female",
      contact: "222-999-6666",
    },
    ref: "REF042",
    deviceId: "DEV042",
    status: "Completed",
  },
  {
    id: "43",
    patient: {
      name: "Benjamin Black",
      avatar: "/path/to/avatar43.jpg",
      age: 28,
      gender: "Male",
      contact: "888-444-7777",
    },
    ref: "REF043",
    deviceId: "DEV043",
    status: "Postponed",
  },
  {
    id: "44",
    patient: {
      name: "Victoria Brown",
      avatar: "/path/to/avatar44.jpg",
      age: 29,
      gender: "Female",
      contact: "333-666-1111",
    },
    ref: "REF044",
    deviceId: "DEV044",
    status: "Due",
  },
  {
    id: "45",
    patient: {
      name: "Dylan Green",
      avatar: "/path/to/avatar45.jpg",
      age: 40,
      gender: "Male",
      contact: "111-999-5555",
    },
    ref: "REF045",
    deviceId: "DEV045",
    status: "Ongoing",
  },
  {
    id: "46",
    patient: {
      name: "Eleanor White",
      avatar: "/path/to/avatar46.jpg",
      age: 33,
      gender: "Female",
      contact: "555-888-4444",
    },
    ref: "REF046",
    deviceId: "DEV046",
    status: "Completed",
  },
  {
    id: "47",
    patient: {
      name: "Isaac Blue",
      avatar: "/path/to/avatar47.jpg",
      age: 31,
      gender: "Male",
      contact: "222-333-7777",
    },
    ref: "REF047",
    deviceId: "DEV047",
    status: "Postponed",
  },
  {
    id: "48",
    patient: {
      name: "Aiden Gray",
      avatar: "/path/to/avatar48.jpg",
      age: 26,
      gender: "Male",
      contact: "444-777-1111",
    },
    ref: "REF048",
    deviceId: "DEV048",
    status: "Due",
  },
  {
    id: "49",
    patient: {
      name: "Harper Black",
      avatar: "/path/to/avatar49.jpg",
      age: 38,
      gender: "Female",
      contact: "111-222-9999",
    },
    ref: "REF049",
    deviceId: "DEV049",
    status: "Ongoing",
  },
  {
    id: "50",
    patient: {
      name: "Jacob Brown",
      avatar: "/path/to/avatar50.jpg",
      age: 45,
      gender: "Male",
      contact: "888-333-2222",
    },
    ref: "REF050",
    deviceId: "DEV050",
    status: "Completed",
  },
];
